---
title: "Compare Gibbs sampling & REML variance components"
author: "Harly Durbin"
output:
  html_document:
    toc: true
    toc_depth: 1
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(glue)
library(purrr)

source(here::here("source_functions/read_gibbs.R"))
source(here::here("source_functions/read_aireml.R"))
```

# Setup 

```{r, warning=FALSE, message=FALSE}
gibbs_corr <-
  purrr::map2_dfr(.x = rep(c(1:5), 
                           times = 6),
                  .y = rep(c(1, 2, 5, 7, 8, 9),
                           times = 5),
                  ~ read_gibbs_corr(iteration = .x,
                                    dataset = .y))
```

```{r, warning=FALSE, message=FALSE}
aireml_corr <-
  purrr::map2_dfr(.x = rep(c(1:5), 
                           times = 6),
                  .y = rep(c(1, 2, 5, 7, 8, 9),
                           times = 5),
                  ~ read_aireml_corr(iteration = .x,
                                     dataset = .y))
```

```{r, warning=FALSE, message=FALSE}
gibbs_varcomp <-
  purrr::map2_dfr(.x = rep(c(1:5), 
                           times = 6),
                  .y = rep(c(1, 2, 5, 7, 8, 9),
                           times = 5),
                  ~ read_gibbs_varcov(iteration = .x,
                                      dataset = .y))
  
```

```{r, warning=FALSE, message=FALSE}
aireml_varcomp <-
  purrr::map2_dfr(.x = rep(c(1:5), 
                           times = 6),
                  .y = rep(c(1, 2, 5, 7, 8, 9),
                           times = 5),
                  ~ read_aireml_varcov(iteration = .x,
                                       dataset = .y))
  
```

# Correlations between estimates

```{r}

aireml_corr %>% 
  rename(aireml_corr = corr) %>% 
  left_join(gibbs_corr %>% 
              rename(gibbs_corr = corr)) %>% 
  group_by(val1, val2) %>% 
  summarise(cor(gibbs_corr, aireml_corr))
```

```{r}
aireml_varcomp %>% 
  rename(aireml_vc = var_cov) %>% 
  left_join(gibbs_varcomp %>% 
              rename(gibbs_vc = var_cov)) %>% 
  group_by(val1, val2) %>% 
  summarise(cor(aireml_vc, gibbs_vc))
  
```
