---
title: "Do genetic trend differ between regions?"
author: "Harly Durbin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
library(purrr)
library(dplyr)
library(tidyr)
library(tidylog)

source(here::here("source_functions/gather_solutions.R"))
source(here::here("source_functions/solutions_line.R"))
```

```{r}
animal_regions <- read_rds(here::here("data/derived_data/animal_regions.rds"))
```

# Notes

```{r}
    region_key <-
      tribble(~num, ~abbrv, ~desc,
              1, "D", "Desert",
              2, "SE", "Southeast",
              3, "HP", "High Plains",
              5, "AP", "Arid Prairie",
              7, "FM", "Forested Mountains",
              8, "FB", "Fescue Belt",
              9, "UMWNE", "Upper Midwest & Northeast")
```




# Import/setup


```{r}
source(here::here("source_functions/datuniv_ped.R"))
```

```{r}

univ_trends <-
  c(
    "data/f90/190812_3v1/D/solutions",
    "data/f90/190812_3v2/SE/solutions",
    "data/f90/190812_3v1/HP/solutions",
    "data/f90/190812_3v5/AP/solutions",
    "data/f90/190812_3v7/FM/solutions",
    "data/f90/190812_3v8/FB/solutions",
    "data/f90/190812_3v9/UMWNE/solutions"
  ) %>%
  set_names(c("1", "2", "3", "5", "7", "8", "9")) %>%
  map(~ read_table2(
    here::here(.x),
    skip = 1,
    col_names = c("trait", "var", "id_univ", "value")
  )) %>%
  imap( ~ mutate(.x, region = .y)) %>%
  reduce(bind_rows) %>%
  # Don't need CG or PE solutions or right now
  filter(var %in% c(2, 3)) %>% 
  select(-trait) %>%
  left_join(
    c(
      "data/f90/190812_3v1/D/renadd02.ped",
      "data/f90/190812_3v2/SE/renadd02.ped",
      "data/f90/190812_3v1/HP/renadd02.ped",
      "data/f90/190812_3v5/AP/renadd02.ped",
      "data/f90/190812_3v7/FM/renadd02.ped",
      "data/f90/190812_3v8/FB/renadd02.ped",
      "data/f90/190812_3v9/UMWNE/renadd02.ped"
    ) %>%
      set_names(c("1", "2", "3", "5", "7", "8", "9")) %>%
      map_dfr( ~ read_table2(here::here(.x),
                             col_names = FALSE),
               .id = "region") %>%
      select(id_univ = X1, id_new = X10, region)
  ) %>% 
  mutate(
    analysis = "univariate",
    region = as.numeric(region),
    var =
      case_when(
        var == 2 ~ "bv_sol",
        var == 3 ~ "mat_sol"
      )
    ) %>% 
  left_join(animal_regions %>% 
              filter(trait == "ww") %>% 
              select(id_new, herd_state, year) %>% 
              distinct())

```


```{r}

biv_trends <-
c(
  "data/f90/190812_3v1/solutions",
  "data/f90/190812_3v2/solutions",
  "data/f90/190812_3v5/solutions",
  "data/f90/190812_3v7/solutions",
  "data/f90/190812_3v8/solutions",
  "data/f90/190812_3v9/solutions"
) %>%
  set_names(c(
    "3v1",
    "3v2", 
    "3v5", 
    "3v7", 
    "3v8",
    "3v9"
    )) %>%
  map(~ read_table2(
    here::here(.x),
    skip = 1,
    col_names = c("trait_region", "var", "id_biv", "value")
  )) %>%
  imap(~ mutate(.x, analysis = .y)) %>% 
  reduce(bind_rows) %>% 
  mutate(
    var =
      case_when(
        var == 1 ~ "cg_sol",
        var == 2 ~ "bv_sol",
        var == 3 ~ "mat_sol",
        var == 4 ~ "mpe"
        ),
    trait_region =
      case_when(
        trait_region == 1 ~ 3,
        trait_region == 2 ~ as.numeric(str_extract(analysis, "(?<=3v)[[:digit:]]"))
      )
    ) %>% 
  left_join(
    c(
      "data/f90/190812_3v1/renadd02.ped",
      "data/f90/190812_3v2/renadd02.ped",
      "data/f90/190812_3v5/renadd02.ped",
      "data/f90/190812_3v7/renadd02.ped",
      "data/f90/190812_3v8/renadd02.ped",
      "data/f90/190812_3v9/renadd02.ped"
      ) %>%
      set_names(
        c(
          "3v1",
          "3v2",
          "3v5",
          "3v7",
          "3v8",
          "3v9"
          )) %>%
      map_dfr(~ read_table2(here::here(.x),
                            col_names = FALSE),
              .id = "analysis") %>%
      select(id_biv = X1, id_new = X10, analysis)
    ) %>% 
  left_join(
    animal_regions %>%
      filter(trait == "ww") %>%
      select(id_new, herd_state, region, year) %>%
      distinct()
  )

```


# From bivariate analyses

```{r, fig.width=10, fig.height=5.4}
biv_trends %>%
  filter(analysis == "3v8") %>%
  filter(id_new %in% datuniv_ped$id_new) %>% 
  filter(region == trait_region) %>% 
  select(-region) %>% 
  rename(region = trait_region) %>% 
  mutate(trait = "ww") %>% 
  solutions_line(
    effect_var = "bv_sol",
    trait_var = "ww",
    y_lab = "Mean breeding value",
    plot_title = "Weaning weight genetic trend, bivariate\nHigh Plains vs. Fescue Belt",
    national_avg = FALSE
)
  
```


```{r, fig.width=10, fig.height=5.4}
biv_trends %>%
  filter(analysis == "3v1") %>% 
  filter(region == trait_region) %>% 
  filter(id_new %in% datuniv_ped$id_new) %>% 
  select(-region) %>% 
  rename(region = trait_region) %>% 
  mutate(trait = "ww") %>% 
  solutions_line(
    effect_var = "mat_sol",
    trait_var = "ww",
    y_lab = "Mean breeding value",
    plot_title = "Weaning weight genetic trend, bivariate\nHigh Plains vs. Desert",
    national_avg = FALSE
)
```

## Weaning weight

```{r, fig.width=14, fig.height=10}
biv_trends %>% 
 # filter(id_new %in% datuniv_ped$id_new) %>% 
  filter(region == trait_region) %>% 
  filter(var == "bv_sol") %>% 
  group_by(analysis, trait_region, year) %>% 
  summarise(mean = mean(value)) %>% 
  mutate(
        line = "solid",
        size = 1
      ) %>%
      # arrange(desc(mean))
      filter(!year %in% c(1972, 2019)) %>%
      ggplot(aes(
        x = year,
        y = mean,
        color = forcats::as_factor(trait_region),
        linetype = line,
        size = size
      )) +
      geom_line(alpha = 0.8,
                key_glyph = "timeseries") +
      scale_linetype_identity(guide = "none") +
      scale_size_identity(guide = "none") +
      scale_color_manual(
        values = c(
          "1" = "tomato2",
          "2" = "darkslategray4",
          "3" = "springgreen3",
          "4" = "brown",
          "5" = "goldenrod1",
          "6" = "gray50",
          "7" = "deeppink3",
          "8" = "gray17",
          "9" = "slateblue2",
          "All regions" = "red"
        ),
        labels = c(
          "1" = "1: Desert",
          "2" = "2: Southeast",
          "3" = "3: High Plains",
          "4" = "4: Rainforest",
          "5" = "5: Arid Prairie",
          "6" = "6: Cold Desert",
          "7" = "7: Forested Mountains",
          "8" = "8: Fescue Belt",
          "9" = "9: Upper Midwest & Northeast",
          "All regions" = "National average"
        )
      ) +
      theme_classic() +
      theme(
        plot.title = element_text(
          size = 22,
          face = "italic",
          margin = margin(
            t = 0,
            r = 0,
            b = 13,
            l = 0
          )
        ),
        axis.title = element_text(size = 16),
        axis.title.y = element_text(margin = margin(
          t = 0,
          r = 13,
          b = 0,
          l = 0
        )),
        axis.title.x = element_text(margin = margin(
          t = 13,
          r = 0,
          b = 0,
          l = 0
        )),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 14),
        strip.text.x = element_text(size = 16)
      ) +
      labs(
        x = NULL,
        y = "Mean weaning weight BV",
        color = NULL,
        linetype = NULL,
        title = "Weaning weight genetic trends estimated from bivariate analyses"
      ) +
  facet_wrap(~analysis, nrow = 2)
```

## Milk

```{r, fig.width=14, fig.height=10}
biv_trends %>% 
 # filter(id_new %in% datuniv_ped$id_new) %>% 
  filter(region == trait_region) %>% 
  filter(var == "mat_sol") %>% 
  group_by(analysis, trait_region, year) %>% 
  summarise(mean = mean(value)) %>% 
  mutate(
        line = "solid",
        size = 1
      ) %>%
      # arrange(desc(mean))
      filter(!year %in% c(1972, 2019)) %>%
      ggplot(aes(
        x = year,
        y = mean,
        color = forcats::as_factor(trait_region),
        linetype = line,
        size = size
      )) +
      geom_line(alpha = 0.8,
                key_glyph = "timeseries") +
      scale_linetype_identity(guide = "none") +
      scale_size_identity(guide = "none") +
      scale_color_manual(
        values = c(
          "1" = "tomato2",
          "2" = "darkslategray4",
          "3" = "springgreen3",
          "4" = "brown",
          "5" = "goldenrod1",
          "6" = "gray50",
          "7" = "deeppink3",
          "8" = "gray17",
          "9" = "slateblue2",
          "All regions" = "red"
        ),
        labels = c(
          "1" = "1: Desert",
          "2" = "2: Southeast",
          "3" = "3: High Plains",
          "4" = "4: Rainforest",
          "5" = "5: Arid Prairie",
          "6" = "6: Cold Desert",
          "7" = "7: Forested Mountains",
          "8" = "8: Fescue Belt",
          "9" = "9: Upper Midwest & Northeast",
          "All regions" = "National average"
        )
      ) +
      theme_classic() +
      theme(
        plot.title = element_text(
          size = 22,
          face = "italic",
          margin = margin(
            t = 0,
            r = 0,
            b = 13,
            l = 0
          )
        ),
        axis.title = element_text(size = 16),
        axis.title.y = element_text(margin = margin(
          t = 0,
          r = 13,
          b = 0,
          l = 0
        )),
        axis.title.x = element_text(margin = margin(
          t = 13,
          r = 0,
          b = 0,
          l = 0
        )),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 14),
        strip.text.x = element_text(size = 16)
      ) +
      labs(
        x = NULL,
        y = "Mean maternal effect solution",
        color = NULL,
        linetype = NULL,
        title = "Milk genetic trends estimated from bivariate analyses"
      ) +
  facet_wrap(~analysis, nrow = 2)
```

# From univariate analyses

## Weaning weight

```{r, fig.width=10, fig.height=5.4}
solutions_line(
  df = univ_trends %>% 
    mutate(trait = "ww") %>% 
    filter(id_new %in% datuniv_ped$id_new),
  effect_var = "bv_sol",
  trait_var = "ww",
  y_lab = "Mean weaning weight BV",
  plot_title = "Weaning weight genetic trend, breeding values\nestimated nby region",
  national_avg = TRUE
)

#ggsave(here::here("figures/regional_ww_trend.png"), width = 10, height = 5.4)
```

## Milk

```{r, fig.width=10, fig.height=5.4}
solutions_line(
  df = univ_trends %>% 
    mutate(trait = "ww") %>% 
    filter(id_new %in% datuniv_ped$id_new),
  effect_var = "mat_sol",
  trait_var = "ww",
  y_lab = "Mean maternal effect solution",
  plot_title = "Milk genetic trend, breeding values\nestimated by region",
  national_avg = TRUE
)


#ggsave(here::here("figures/regional_milk_trend.png"), width = 10, height = 5.4)
```



