---
title: "Genetic correlations & variance components from bivariate Gibbs sampling models"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(readr)
library(dplyr)
library(tidyr)
library(glue)
library(magrittr)
library(tibble)
library(purrr)
library(ggplot2)
library(stringr)

complete_samples <- 8897

source(here::here("source_functions/calculate_heritability.R"))
source(here::here("source_functions/read_gibbs.R"))
source(here::here("source_functions/region_key.R"))

```

# Notes & questions

# Setup 

```{r, message= FALSE, warning=FALSE}
gibbs_samples <-
  purrr::map2_dfr(.x = rep(c(1:5), 
                           times = 6),
                  .y = rep(c(1, 2, 5, 7, 8, 9),
                           times = 5),
                  ~ read_gibbs_samples(iteration = .x,
                                 region = .y)) %>% 
  select(iter, dataset, everything(), -X1, -X3) %>% 
  purrr::set_names("iter", "dataset", "round", c(1:14)) %>% 
  tidyr::pivot_longer(cols = c(`1`:`14`),
                      names_to = "param") %>% 
  mutate(param = case_when(param == "1" ~ "d1d1",
                           param == "2" ~ "d1d2",
                           param == "3" ~ "d1m1",
                           param == "4" ~ "d1m2",
                           param == "5" ~ "d2d2",
                           param == "6" ~ "d2m1",
                           param == "7" ~ "d2m2",
                           param == "8" ~ "m1m1",
                           param == "9" ~ "m1m2",
                           param == "10" ~ "m2m2",
                           param == "11" ~ "mpe1mpe1",
                           param == "12" ~ "mpe2mpe2",
                           param == "13" ~ "r1r1",
                           param == "14" ~ "r2r2"),
         iter = as.character(iter))
  
``` 

```{r}
n_samples <-
  gibbs_samples %>% 
  group_by(iter, dataset, param) %>% 
  tally(name = "n_samples") %>% 
  ungroup() %>% 
  mutate(iter = as.numeric(iter)) %>% 
  distinct(iter, dataset, n_samples) 
```

```{r, warning=FALSE, message=FALSE}
gibbs_varcomp <-
  purrr::map2_dfr(.x = rep(c(1:5), 
                           times = 6),
                  .y = rep(c(1, 2, 5, 7, 8, 9),
                           times = 5),
                  ~ read_gibbs_varcov(iteration = .x,
                                      dataset = .y) %>% 
                    mutate(dataset = glue("3v{.y}")))
  
```

```{r, warning=FALSE, message=FALSE}
gibbs_corr <-
  purrr::map2_dfr(.x = rep(c(1:5), 
                           times = 6),
                  .y = rep(c(1, 2, 5, 7, 8, 9),
                           times = 5),
                  ~ read_gibbs_corr(iteration = .x,
                                    dataset = .y) %>% 
                    mutate(dataset = glue("3v{.y}")))
```

```{r, warning=FALSE, message=FALSE}
gibbs_h2 <-
  purrr::map2_dfr(.x = rep(c(1:5), 
                           times = 6),
                  .y = rep(c(1, 2, 5, 7, 8, 9),
                           times = 5),
                  ~ read_gibbs_h2(iteration = .x,
                                  dataset = .y) %>% 
                    mutate(dataset = glue("3v{.y}"))) 
```

# Heritabilities

```{r}
gibbs_h2 %>% 
  left_join(n_samples) %>% 
  filter(n_samples >= complete_samples) %>% 
  select(Comparison = key, Iteration = iter, everything(), -n_samples) %>%
  arrange(Comparison, Iteration)
```

## $h^2_D$

```{r}
gibbs_h2 %>% 
  group_by(key) %>% 
  summarise(`Min h2D` = min(`Direct h2`),
            `Mean h2D` = mean(`Direct h2`),
            `Max h2D` = max(`Direct h2`),
            n = n())
  
``` 

## $h^2_M$

```{r}
gibbs_h2 %>% 
  group_by(key) %>% 
  summarise(`Min h2M` = min(`Maternal h2`),
            `Mean h2M` = mean(`Maternal h2`),
            `Max h2M` = max(`Maternal h2`),
            n = n())
  
``` 

## $c^2$

```{r}
gibbs_h2 %>% 
  group_by(key) %>% 
  summarise(`Min c2` = min(`MPE c2`),
            `Mean c2` = mean(`MPE c2`),
            `Max c2` = max(`MPE c2`),
            n = n())
  
``` 

# Genetic correlations

## HP direct & other direct

```{r}
gibbs_corr %>% 
  filter(stringr::str_detect(val1, "3_dir")) %>% 
  filter(stringr::str_detect(val2, "dir") & !stringr::str_detect(val2, "3")) %>% 
  mutate(num = as.numeric(stringr::str_extract(val2, "[1-9]"))) %>% 
  left_join(region_key %>% 
              select(num, desc)) %>% 
  left_join(n_samples) %>% 
  filter(n_samples >= complete_samples) %>% 
  select(Comparison = desc,
         Iteration = iter,
         Correlation = corr) %>% 
  arrange(Comparison, Iteration)
```

```{r}
gibbs_corr %>% 
  filter(str_detect(val1, "3_dir")) %>% 
  filter(str_detect(val2, "dir") & !str_detect(val2, "3")) %>% 
  mutate(num = as.numeric(str_extract(val2, "[1-9]"))) %>% 
  left_join(region_key %>% 
              select(num, desc)) %>% 
  left_join(n_samples) %>% 
  filter(n_samples >= complete_samples) %>% 
  select(Comparison = desc,
         Iteration = iter,
         Correlation = corr) %>% 
  group_by(Comparison) %>% 
  summarise(`Min.` = min(Correlation),
            Mean = mean(Correlation),
            `Max.` = max(Correlation),
            SD = sd(Correlation))
```

## HP maternal & other maternal

```{r}
gibbs_corr %>% 
  filter(str_detect(val1, "3_mat")) %>% 
  filter(str_detect(val2, "mat") & !str_detect(val2, "3")) %>% 
  mutate(num = as.numeric(str_extract(val2, "[1-9]"))) %>% 
  left_join(region_key %>% 
              select(num, desc)) %>% 
  left_join(n_samples) %>% 
  filter(n_samples >= complete_samples) %>%
  select(Comparison = desc,
         Iteration = iter,
         Correlation = corr) %>% 
  arrange(Comparison, Iteration)
```

```{r}
gibbs_corr %>% 
  filter(str_detect(val1, "3_mat")) %>% 
  filter(str_detect(val2, "mat") & !str_detect(val2, "3")) %>% 
  mutate(num = as.numeric(str_extract(val2, "[1-9]"))) %>% 
  left_join(region_key %>% 
              select(num, desc)) %>%
  left_join(n_samples) %>% 
  filter(n_samples >= complete_samples) %>%
  select(Comparison = desc,
         Iteration = iter,
         Correlation = corr) %>% 
  group_by(Comparison) %>% 
  summarise(`Min.` = min(Correlation),
            Mean = mean(Correlation),
            `Max.` = max(Correlation),
            SD = sd(Correlation))
```

## HP direct & other maternal

```{r}
gibbs_corr %>% 
  filter(str_detect(val1, "3_dir")) %>% 
  filter(str_detect(val2, "mat") & !str_detect(val2, "3")) %>% 
  mutate(num = as.numeric(str_extract(val2, "[1-9]"))) %>% 
  left_join(region_key %>% 
              select(num, desc)) %>%
  left_join(n_samples) %>% 
  filter(n_samples >= complete_samples) %>%
  select(Comparison = desc,
         Iteration = iter,
         Correlation = corr) %>% 
  group_by(Comparison) %>% 
  summarise(`Min.` = min(Correlation),
            Mean = mean(Correlation),
            `Max.` = max(Correlation),
            SD = sd(Correlation))
```

## Within-region direct & maternal

```{r}
gibbs_corr %>% 
  mutate(val1r = str_extract(val1, "^[[:digit:]]{1}"),
         val2r = str_extract(val2, "^[[:digit:]]{1}")) %>% 
  filter(val1r == val2r) %>% 
  filter(str_detect(val1, "dir")) %>% 
  filter(str_detect(val2, "mat")) %>% 
  mutate(num = as.numeric(str_extract(val2, "[1-9]"))) %>% 
  left_join(region_key %>% 
              select(num, desc)) %>%
  left_join(n_samples) %>% 
  filter(n_samples >= complete_samples) %>%
  select(Comparison = desc,
         Iteration = iter,
         Correlation = corr) %>% 
  group_by(Comparison) %>% 
  summarise(`Min.` = min(Correlation),
            Mean = mean(Correlation),
            `Max.` = max(Correlation),
            SD = sd(Correlation))
```