---
title: "Untitled"
author: "Harly Durbin"
date: "8/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(purrr)
library(magrittr)
library(glue)
library(tidylog)

source(here::here("source_functions/sample_until.R"))
source(here::here("source_functions/three_gen.R"))

region_key <-
  tribble(~num, ~abbrv, ~desc,
          2, "SE", "Southeast",
          8, "FB", "Fescue Belt",
          3, "HP", "High Plains", 
          5, "AP", "Arid Prairie",
          7, "FM", "Forested Mountains", 
          1, "D", "Desert",
          9, "UMWNE", "Upper Midwest & Northeast")

```

# Setup

```{r}
animal_regions <- read_rds(here::here("data/derived_data/animal_regions.rds"))
cg_regions <- read_rds(here::here("data/derived_data/cg_regions.rds"))
ped <- read_rds(here::here("data/derived_data/ped.rds"))
```

# Start data


```{r}
start <-
  animal_regions %>%
  # Only weaning weights
  filter(trait == "ww") %>%
  filter(var == "weight") %>%
  filter(region %in% c(3, 5, 1, 7, 9)) %>%
  left_join(ped) %>%
  # Keep only contemporary groups with 15 or more animals
  filter(n_animals >= 15) %>%
  group_by(cg_new) %>%
  # Remove single sire single dam contemporary groups
  filter(n_distinct(sire_id) > 1) %>%
  filter(n_distinct(dam_id) > 1) %>%
  ungroup() %>%
  group_by(zip) %>%
  # At least 10 years of data
  filter(n_distinct(year) >= 10) %>%
  ungroup() %>% 
  mutate(
    helper = 
      case_when(
        herd_state %in% c("CA", "OR", "ID", "WA") & region == 9 ~ "drop",
        TRUE ~ "keep"
      )) %>% 
  filter(helper == "keep")


#8/22: redo SE (wasn't comparing to same HP)


start_se <-
  animal_regions %>%
  # Only weaning weights
  filter(trait == "ww") %>%
  filter(var == "weight") %>%
  filter(region %in% c(2)) %>%
  left_join(ped) %>%
  # Keep only contemporary groups with 15 or more animals
  filter(n_animals >= 15) %>%
  group_by(cg_new) %>%
  # Remove single sire single dam contemporary groups
  filter(n_distinct(sire_id) > 1) %>%
  filter(n_distinct(dam_id) > 1) %>%
  ungroup() %>%
  group_by(zip) %>%
  # At least 10 years of data
  filter(n_distinct(year) >= 10) %>%
  ungroup() %>% 
  mutate(
    helper = 
      case_when(
        herd_state %in% c("CA") & region == 2 ~ "drop",
        TRUE ~ "keep"
      )) %>% 
  filter(helper == "keep")
```

# Sample

```{r, dkeep}
# Region 1: Desert

d_keep <-
  cg_regions %>% 
  filter(trait == "ww") %>% 
  filter(cg_new %in% start$cg_new) %>% 
  filter(region == 1) %>% 
  group_by(zip) %>%
  summarise(n_years = n_distinct(year),
            n_records = sum(n_animals)) %>% 
  ungroup() %>% 
  # summarise(sum(n_records))
  sample_until(limit = 99800, region_id = 1)

d_keep %>% 
  summarise(sum(n_records), 
            n_distinct(zip))
```

```{r}

# Region 2: Southeast

se_keep <-
  cg_regions %>% 
  filter(trait == "ww") %>% 
  filter(cg_new %in% start_se$cg_new) %>% 
  filter(region == 2) %>% 
  group_by(zip) %>%
  summarise(n_years = n_distinct(year),
            n_records = sum(n_animals)) %>% 
  ungroup() %>% 
  # summarise(sum(n_records))
  sample_until(limit = 100000, region_id = 2)


se_keep %>% 
  summarise(sum(n_records), 
            n_distinct(zip))
```

```{r}

# Region 5: Arid Prairie

ap_keep <-
  cg_regions %>% 
  filter(trait == "ww") %>% 
  filter(cg_new %in% start$cg_new) %>% 
  filter(region == 5) %>% 
  group_by(zip) %>%
  summarise(n_years = n_distinct(year),
            n_records = sum(n_animals)) %>% 
  ungroup() %>% 
  # summarise(sum(n_records))
  sample_until(limit = 99900, region_id = 5)


ap_keep %>% 
  summarise(sum(n_records), 
            n_distinct(zip))
```

```{r}
# Region 7: Forested Mountains

fm_keep <-
  cg_regions %>% 
  filter(trait == "ww") %>% 
  filter(cg_new %in% start$cg_new) %>% 
  filter(region == 7) %>% 
  group_by(zip) %>%
  summarise(n_years = n_distinct(year),
            n_records = sum(n_animals)) %>% 
  ungroup() %>% 
  # summarise(sum(n_records))
  sample_until(limit = 100000, region_id = 7)


fm_keep %>% 
  summarise(sum(n_records), 
            n_distinct(zip))
```

```{r}
# Region 9: Upper Midwest & NE

umwne_keep <-
  cg_regions %>% 
  filter(trait == "ww") %>% 
  filter(cg_new %in% start$cg_new) %>% 
  filter(region == 9) %>% 
  group_by(zip) %>% 
  summarise(n_years = n_distinct(year),
            n_records = sum(n_animals)) %>% 
  ungroup() %>% 
  # summarise(sum(n_records))
  sample_until(limit = 99900, region_id = 9)

umwne_keep %>% 
  summarise(sum(n_records), 
            n_distinct(zip))
```

# Bind sampled data, sanity check

```{r}
all_keep <- 
  bind_rows(ap_keep, d_keep, fm_keep, umwne_keep, hp_keep) %>% 
  distinct()
```

```{r}
start %>% 
  filter(zip %in% all_keep$zip) %>% 
  group_by(herd_state) %>% 
  tally(sort = TRUE)
```

```{r}
start_se %>% 
  filter(zip %in% se_keep$zip) %>% 
  group_by(herd_state) %>% 
  tally(sort = TRUE)
```

```{r}
start %>% 
  filter(zip %in% all_keep$zip) %>% 
  group_by(sire_id, region) %>% 
  tally(sort = TRUE) %>% 
  ungFroup() %>% 
  group_by(sire_id) %>% 
  filter(n_distinct(region) > 1) %>% 
  ungroup() %>% 
  tidyr::pivot_wider(
    id_cols = c("sire_id"),
    names_from = region,
    values_from = n,
    names_prefix = "n_"
  )
```

# Univariate 

## Copy HP data

```{r}

copy_hp <-
  function(region2) {
    
     run_dir <- glue("data/f90/190812_3v{region2}")

     if (!dir.exists(here::here(glue("{run_dir}/HP")))) {
       dir.create(here::here(run_dir))
     }
    
    file.copy(here::here("data/f90/190812_3v8/HP/"), here::here(run_dir), recursive = TRUE)
    
  }

list("2") %>% 
walk(~ copy_hp(region2 = .x))
```


## Data

```{r}
## ----univariate data-----------------------------------------------------

start %>% 
  filter(zip %in% all_keep$zip) %>% 
  filter(region != 3) %>% 
  mutate(key =
           case_when(
             region == 1 ~ "D",
             region == 5 ~ "AP",
             region == 7 ~ "FM",
             region == 9 ~ "UMWNE"
           )) %>%
  select(key, id_new, cg_new, value, region) %>% 
  group_by(key) %>% 
  group_walk(~ write_delim(.x %>% 
                             select(-region),
                           path = here::here(
                             glue::glue("data/f90/190812_3v{unique(.$region)}/{.y}/data.{.y}.txt")
                             ),
                           delim = " ",
                           col_names = FALSE))

```

```{r}
start_se %>%
  filter(zip %in% se_keep$zip) %>%
  select(id_new, cg_new, value) %>% 
  write_delim(
    path = here::here("data/f90/190812_3v2/SE/data.SE.txt"),
    delim = " ",
    col_names = FALSE
  )
  
```


## Ped

```{r}
start %>% 
  filter(zip %in% all_keep$zip) %>% 
  filter(region != 3) %>% 
  mutate(key =
           case_when(
             region == 1 ~ "D",
             region == 5 ~ "AP",
             region == 7 ~ "FM",
             region == 9 ~ "UMWNE"
           )) %>%
  select(key, id_new, region) %>% 
  left_join(ped %>%
              select(1:3)) %>% 
  group_by(key) %>%
  group_map( ~ three_gen2(df = .x, full_ped = ped, region_id = unique(.x$region)), keep = TRUE) %>%
  set_names(c("AP", "D", "FM", "UMWNE")) %>% 
  iwalk(~ write_delim(
    .x %>% 
      select(-region),
    path = here::here(glue::glue(
      "data/f90/190812_3v{unique(.$region)}/{.y}/ped.{.y}.txt"
    )),
    delim = " ",
    col_names = FALSE
  ))


```

```{r}
start_se %>% 
  filter(zip %in% se_keep$zip) %>% 
  select(id_new) %>% 
  left_join(ped %>%
              select(1:3)) %>% 
  three_gen(full_ped = ped) %>% 
  write_delim(
    path = here::here("data/f90/190812_3v2/SE/ped.SE.txt"),
    delim = " ",
    col_names = FALSE
  )
```


# Bivariate

## Data

```{r}

write_biv <-
  function(region2) {
    
    abbrv <- 
      region_key %>% 
      filter(num == region2) %>% 
      pull(abbrv)
    
    start %>%
      filter(zip %in% all_keep$zip) %>%
      filter(region %in% c(3, region2)) %>%
      select(region, id_new, cg_new, value) %>%
      spread(region, value) %>%
      mutate_all( ~ replace_na(., "0")) %>%
      arrange(`3`) %>%
      select(id_new, cg_new, `3`, everything()) %>% 
      write_delim(
        here::here(glue("data/f90/190812_3v{region2}/data.HP_{abbrv}.txt")),
        delim = " ",
        col_names = FALSE
      )
  }


list("9", "5", "1", "7") %>% 
walk(~ write_biv(region2 = .x))

```

```{r}
read_table2(
  here::here("data/f90/190812_3v8/HP/data.HP.txt"),
  col_names = c("id_new", "cg_new", "value")
) %>%
  mutate(region = 3) %>%
  bind_rows(start_se %>%
              filter(zip %in% se_keep$zip) %>%
              select(id_new, cg_new, value, region)) %>%
  spread(region, value) %>%
  mutate_all(~ replace_na(., "0")) %>%
  arrange(`3`) %>%
  select(id_new, cg_new, `3`, everything()) %>%
  write_delim(here::here(glue(
    "data/f90/190812_3v2/data.HP_SE.txt"
  )),
  delim = " ",
  col_names = FALSE)
```


## Ped

```{r}

write_biv_ped <-
  function(region2) {
    
    abbrv <-
      region_key %>%
      filter(num == region2) %>%
      pull(abbrv)
    
    start %>%
      filter(zip %in% all_keep$zip) %>%
      filter(region %in% c(3, region2)) %>%
      select(id_new) %>%
      left_join(ped %>%
                  select(1:3)) %>%
      three_gen(full_ped = ped) %>%
      distinct() %>%
      write_delim(here::here(glue(
        "data/f90/190812_3v{region2}/ped.HP_{abbrv}.txt"
      )),
      delim = " ",
      col_names = FALSE)

  }

list("9", "5", "1", "7") %>% 
walk(~ write_biv_ped(region2 = .x))
```

```{r}
read_table2(
  here::here("data/f90/190812_3v8/HP/data.HP.txt"),
  col_names = c("id_new", "cg_new", "value")
) %>%
  select(id_new) %>% 
  bind_rows(start_se %>%
              filter(zip %in% se_keep$zip) %>%
              select(id_new)) %>% 
  left_join(ped %>%
              select(1:3)) %>% 
  three_gen(full_ped = ped) %>% 
  write_delim(
    path = here::here("data/f90/190812_3v2/ped.HP_SE.txt"),
    delim = " ",
    col_names = FALSE
  )
```

## Par

```{r}

copy_par <-
  function(region2) {
    
    abbrv <-
      region_key %>%
      filter(num == region2) %>%
      pull(abbrv)
    
     run_dir <- glue("data/f90/190812_3v{region2}")
     
     file.copy(from = here::here("data/f90/190812_3v8/HP_FB.par"), to = here::here(run_dir), recursive = FALSE, copy.mode = TRUE)
     
     file.rename(here::here(glue("{run_dir}/HP_FB.par")), here::here(glue("{run_dir}/HP_{abbrv}.par")))
    
  }

list("2") %>% 
walk(~ copy_par(region2 = .x))
```