# Extract renamed id, renamed sire id, renamed dam id, orginal id (registration number) from `renadd02.ped` generated by `renumf90`
# Append embryo transfer key from `Growth_ET.csv`
# Append birth year from `Growth_BirthYr.csv`
# Remove generated duplicates 

pull_ped <-
  function(refresh = FALSE) {
    if (refresh == TRUE) {

        read_table2(here::here("data/raw_data/renadd02.ped"),
                    col_names = FALSE) %>%
        rename(id_new = X1,
               sire_id = X2,
               dam_id = X3) %>%
        select(1:3, 10) %>%
        mutate(
          registration_number = str_extract(X10, "[[:digit:]]+"),
          reg_type = str_extract(X10, "[[:upper:]]+")
        ) %>%
        select(-X10) %>%
        mutate(full_reg = as.character(glue::glue("{reg_type}{registration_number}"))) %>%
        # Key of embryo transfer animals
        left_join(
          read_csv(here::here("data/raw_data/Growth_ET.csv")) %>%
            mutate(
              registration_number = str_extract(REG_NUM, "[[:digit:]]+"),
              reg_type = str_extract(REG_NUM, "[[:upper:]]+"),
              full_reg = as.character(
                glue::glue("{reg_type}{registration_number}")
              )
            ) %>%
            select(-REG_NUM) %>%
            rename(et_status = IS_ET)
        ) %>%
        # Key of birth years
        left_join(
          read_csv(here::here("data/raw_data/Growth_BirthYr.csv")) %>%
            mutate(
              registration_number = str_extract(REG_NUM, "[[:digit:]]+"),
              reg_type = str_extract(REG_NUM, "[[:upper:]]+"),
              full_reg = as.character(
                glue::glue("{reg_type}{registration_number}")
              )
            ) %>%
            select(registration_number, reg_type, full_reg, birth_year = BIRTH_YR)
        ) %>%
        group_by(full_reg) %>%
        slice(1) %>%
        ungroup()

    }

    else {
      read_rds(here::here("data/derived_data/import_regions/ped.rds"))

    }

  }
